package ilert

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"strconv"
)

// Postmortem definition https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortems
//
// An incident keeps one postmortem, either generated by ilert or linked to a document hosted
// elsewhere. The API only enforces that for requests sent one after another: requests or links for
// the same incident sent concurrently can each create one. The operations below only return the id, status, visibility, markdown url, link url,
// error message, creator and creation date; the other fields are part of the documented schema but
// left empty by them.
type Postmortem struct {
	ID int64 `json:"id,omitempty"`

	// the generation status, read-only
	// possible values: "NONE", "REQUESTED", "STARTED", "CREATED", "LINKED", "ERROR"
	Status string `json:"status,omitempty"`

	Title string `json:"title,omitempty"`

	// possible values: "AI_DRAFT", "DRAFT", "IN_REVIEW", "PUBLISHED"
	EditorialStatus string `json:"editorialStatus,omitempty"`

	// possible values: "NONE", "PRIVATE", "PUBLIC"
	Visibility string `json:"visibility,omitempty"`

	// location of the generated postmortem document
	MarkdownURL string `json:"markdownUrl,omitempty"`

	// link to an externally hosted postmortem document
	LinkURL string `json:"linkUrl,omitempty"`

	MarkdownContent string `json:"markdownContent,omitempty"`

	// set when the status is ERROR, read-only
	ErrorMessage string `json:"errorMessage,omitempty"`

	Creator   *User     `json:"creator,omitempty"`
	Incident  *Incident `json:"incident,omitempty"`
	CreatedAt string    `json:"createdAt,omitempty"` // Date time string in ISO format
	UpdatedAt string    `json:"updatedAt,omitempty"` // Date time string in ISO format
}

// PostmortemRequest is the context a postmortem is generated from
type PostmortemRequest struct {
	// alerts to take into account
	Alerts []PostmortemRequestReference `json:"alerts,omitempty"`

	// deployment events to take into account
	Deployments []PostmortemRequestReference `json:"deployments,omitempty"`

	// chat channels whose transcript is taken into account. Only Slack channels are, the API
	// drops channels of any other type from the request without an error.
	Channels []PostmortemRequestChannel `json:"channels,omitempty"`

	Impact         string `json:"impact,omitempty"`
	RootCause      string `json:"rootCause,omitempty"`
	ActionItems    string `json:"actionItems,omitempty"`
	ChatTranscript string `json:"chatTranscript,omitempty"`

	// possible values: "NONE", "PRIVATE", "PUBLIC"
	Visibility string `json:"visibility,omitempty"`

	// IANA time zone name used for dates in the generated document, for example Europe/Berlin
	Timezone string `json:"timezone,omitempty"`

	// language of the generated document, for example en or de
	Language string `json:"language,omitempty"`
}

// PostmortemRequestReference references an alert or a deployment event by id
type PostmortemRequestReference struct {
	ID int64 `json:"id"`
}

// PostmortemRequestChannel references a chat channel and the time window of its transcript
type PostmortemRequestChannel struct {
	ID string `json:"id,omitempty"`

	// possible values: "SLACK", "MS_TEAMS", "GOOGLE_CHAT"
	Type string `json:"type,omitempty"`

	GroupID       string `json:"groupId,omitempty"`
	IsPrivate     bool   `json:"isPrivate,omitempty"`
	FromEpochSec  int64  `json:"fromEpochSec,omitempty"`
	UntilEpochSec int64  `json:"untilEpochSec,omitempty"`
}

// PostmortemStatus defines postmortem status
var PostmortemStatus = struct {
	None      string
	Requested string
	Started   string
	Created   string
	Linked    string
	Error     string
}{
	None:      "NONE",
	Requested: "REQUESTED",
	Started:   "STARTED",
	Created:   "CREATED",
	Linked:    "LINKED",
	Error:     "ERROR",
}

// PostmortemStatusAll defines postmortem status list
var PostmortemStatusAll = []string{
	PostmortemStatus.None,
	PostmortemStatus.Requested,
	PostmortemStatus.Started,
	PostmortemStatus.Created,
	PostmortemStatus.Linked,
	PostmortemStatus.Error,
}

// PostmortemEditorialStatus defines postmortem editorial status
var PostmortemEditorialStatus = struct {
	AiDraft   string
	Draft     string
	InReview  string
	Published string
}{
	AiDraft:   "AI_DRAFT",
	Draft:     "DRAFT",
	InReview:  "IN_REVIEW",
	Published: "PUBLISHED",
}

// PostmortemEditorialStatusAll defines postmortem editorial status list
var PostmortemEditorialStatusAll = []string{
	PostmortemEditorialStatus.AiDraft,
	PostmortemEditorialStatus.Draft,
	PostmortemEditorialStatus.InReview,
	PostmortemEditorialStatus.Published,
}

// PostmortemVisibility defines postmortem visibility
var PostmortemVisibility = struct {
	None    string
	Private string
	Public  string
}{
	None:    "NONE",
	Private: "PRIVATE",
	Public:  "PUBLIC",
}

// PostmortemVisibilityAll defines postmortem visibility list
var PostmortemVisibilityAll = []string{
	PostmortemVisibility.None,
	PostmortemVisibility.Private,
	PostmortemVisibility.Public,
}

// GetIncidentPostmortemsInput represents the input of a GetIncidentPostmortems operation.
type GetIncidentPostmortemsInput struct {
	_          struct{}
	IncidentID *int64
}

// GetIncidentPostmortemsOutput represents the output of a GetIncidentPostmortems operation.
type GetIncidentPostmortemsOutput struct {
	_           struct{}
	Postmortems []*Postmortem
}

// GetIncidentPostmortems lists the postmortems of an incident. https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortems
func (c *Client) GetIncidentPostmortems(input *GetIncidentPostmortemsInput) (*GetIncidentPostmortemsOutput, error) {
	if input == nil {
		return nil, errors.New("input is required")
	}
	if input.IncidentID == nil {
		return nil, errors.New("incident id is required")
	}

	resp, err := c.httpClient.R().Get(fmt.Sprintf("%s/%d/postmortems", apiRoutes.incidents, *input.IncidentID))
	if err != nil {
		return nil, err
	}
	if apiErr := getGenericAPIError(resp, 200); apiErr != nil {
		return nil, apiErr
	}

	postmortems := make([]*Postmortem, 0)
	err = json.Unmarshal(resp.Body(), &postmortems)
	if err != nil {
		return nil, err
	}

	return &GetIncidentPostmortemsOutput{Postmortems: postmortems}, nil
}

// GetIncidentPostmortemInput represents the input of a GetIncidentPostmortem operation.
type GetIncidentPostmortemInput struct {
	_            struct{}
	IncidentID   *int64
	PostmortemID *int64
}

// GetIncidentPostmortemOutput represents the output of a GetIncidentPostmortem operation.
type GetIncidentPostmortemOutput struct {
	_          struct{}
	Postmortem *Postmortem
}

// GetIncidentPostmortem gets a postmortem of an incident by id. https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortems
func (c *Client) GetIncidentPostmortem(input *GetIncidentPostmortemInput) (*GetIncidentPostmortemOutput, error) {
	if input == nil {
		return nil, errors.New("input is required")
	}
	if input.IncidentID == nil {
		return nil, errors.New("incident id is required")
	}
	if input.PostmortemID == nil {
		return nil, errors.New("postmortem id is required")
	}

	resp, err := c.httpClient.R().Get(fmt.Sprintf("%s/%d/postmortems/%d", apiRoutes.incidents, *input.IncidentID, *input.PostmortemID))
	if err != nil {
		return nil, err
	}
	if apiErr := getGenericAPIError(resp, 200); apiErr != nil {
		return nil, apiErr
	}

	postmortem := &Postmortem{}
	err = json.Unmarshal(resp.Body(), postmortem)
	if err != nil {
		return nil, err
	}

	return &GetIncidentPostmortemOutput{Postmortem: postmortem}, nil
}

// RequestIncidentPostmortemInput represents the input of a RequestIncidentPostmortem operation.
type RequestIncidentPostmortemInput struct {
	_          struct{}
	IncidentID *int64
	Request    *PostmortemRequest

	// replaces the postmortem the incident already has. Without it the API rejects the request
	// when there is one.
	Overwrite *bool
}

// RequestIncidentPostmortemOutput represents the output of a RequestIncidentPostmortem operation.
type RequestIncidentPostmortemOutput struct {
	_          struct{}
	Postmortem *Postmortem
}

// RequestIncidentPostmortem requests the generation of a postmortem for an incident. The generation
// runs asynchronously, the returned postmortem reports its progress in Status and the document is
// available at MarkdownURL once it is CREATED. Needs the postmortem feature on the account. https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortems
func (c *Client) RequestIncidentPostmortem(input *RequestIncidentPostmortemInput) (*RequestIncidentPostmortemOutput, error) {
	if input == nil {
		return nil, errors.New("input is required")
	}
	if input.IncidentID == nil {
		return nil, errors.New("incident id is required")
	}
	if input.Request == nil {
		return nil, errors.New("postmortem request input is required")
	}

	resp, err := c.httpClient.R().SetBody(input.Request).Post(fmt.Sprintf("%s/%d/postmortems%s", apiRoutes.incidents, *input.IncidentID, overwriteQuery(input.Overwrite)))
	if err != nil {
		return nil, err
	}
	if apiErr := getGenericAPIError(resp, 201); apiErr != nil {
		return nil, apiErr
	}

	postmortem := &Postmortem{}
	err = json.Unmarshal(resp.Body(), postmortem)
	if err != nil {
		return nil, err
	}

	return &RequestIncidentPostmortemOutput{Postmortem: postmortem}, nil
}

// LinkIncidentPostmortemInput represents the input of a LinkIncidentPostmortem operation.
type LinkIncidentPostmortemInput struct {
	_          struct{}
	IncidentID *int64

	// LinkURL is required. The API sets Visibility to NONE when it is left empty.
	Postmortem *Postmortem

	// replaces the postmortem the incident already has. Without it the API rejects the request
	// when there is one.
	Overwrite *bool
}

// LinkIncidentPostmortemOutput represents the output of a LinkIncidentPostmortem operation.
type LinkIncidentPostmortemOutput struct {
	_          struct{}
	Postmortem *Postmortem
}

// LinkIncidentPostmortem links an externally hosted postmortem document to an incident. https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortem-links
func (c *Client) LinkIncidentPostmortem(input *LinkIncidentPostmortemInput) (*LinkIncidentPostmortemOutput, error) {
	if input == nil {
		return nil, errors.New("input is required")
	}
	if input.IncidentID == nil {
		return nil, errors.New("incident id is required")
	}
	if input.Postmortem == nil {
		return nil, errors.New("postmortem input is required")
	}
	if input.Postmortem.LinkURL == "" {
		return nil, errors.New("postmortem link url is required")
	}

	resp, err := c.httpClient.R().SetBody(input.Postmortem).Post(fmt.Sprintf("%s/%d/postmortem-links%s", apiRoutes.incidents, *input.IncidentID, overwriteQuery(input.Overwrite)))
	if err != nil {
		return nil, err
	}
	if apiErr := getGenericAPIError(resp, 201); apiErr != nil {
		return nil, apiErr
	}

	postmortem := &Postmortem{}
	err = json.Unmarshal(resp.Body(), postmortem)
	if err != nil {
		return nil, err
	}

	return &LinkIncidentPostmortemOutput{Postmortem: postmortem}, nil
}

// UpdateIncidentPostmortemInput represents the input of a UpdateIncidentPostmortem operation.
type UpdateIncidentPostmortemInput struct {
	_            struct{}
	IncidentID   *int64
	PostmortemID *int64

	// Status has to be LINKED and LinkURL set. The API sets Visibility to NONE when it is left
	// empty, so send the current one to keep it.
	Postmortem *Postmortem
}

// UpdateIncidentPostmortemOutput represents the output of a UpdateIncidentPostmortem operation.
type UpdateIncidentPostmortemOutput struct {
	_          struct{}
	Postmortem *Postmortem
}

// UpdateIncidentPostmortem updates a postmortem of an incident. The only update the API accepts is
// turning the postmortem into a LINKED one, or changing the link and visibility of one that already
// is. https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortems
func (c *Client) UpdateIncidentPostmortem(input *UpdateIncidentPostmortemInput) (*UpdateIncidentPostmortemOutput, error) {
	if input == nil {
		return nil, errors.New("input is required")
	}
	if input.IncidentID == nil {
		return nil, errors.New("incident id is required")
	}
	if input.PostmortemID == nil {
		return nil, errors.New("postmortem id is required")
	}
	if input.Postmortem == nil {
		return nil, errors.New("postmortem input is required")
	}

	resp, err := c.httpClient.R().SetBody(input.Postmortem).Put(fmt.Sprintf("%s/%d/postmortems/%d", apiRoutes.incidents, *input.IncidentID, *input.PostmortemID))
	if err != nil {
		return nil, err
	}
	if apiErr := getGenericAPIError(resp, 200); apiErr != nil {
		return nil, apiErr
	}

	postmortem := &Postmortem{}
	err = json.Unmarshal(resp.Body(), postmortem)
	if err != nil {
		return nil, err
	}

	return &UpdateIncidentPostmortemOutput{Postmortem: postmortem}, nil
}

// DeleteIncidentPostmortemInput represents the input of a DeleteIncidentPostmortem operation.
type DeleteIncidentPostmortemInput struct {
	_            struct{}
	IncidentID   *int64
	PostmortemID *int64
}

// DeleteIncidentPostmortemOutput represents the output of a DeleteIncidentPostmortem operation.
type DeleteIncidentPostmortemOutput struct {
	_ struct{}
}

// DeleteIncidentPostmortem deletes a postmortem of an incident. https://docs.ilert.com/developer-docs/rest-api/api-reference/incident-postmortems
func (c *Client) DeleteIncidentPostmortem(input *DeleteIncidentPostmortemInput) (*DeleteIncidentPostmortemOutput, error) {
	if input == nil {
		return nil, errors.New("input is required")
	}
	if input.IncidentID == nil {
		return nil, errors.New("incident id is required")
	}
	if input.PostmortemID == nil {
		return nil, errors.New("postmortem id is required")
	}

	resp, err := c.httpClient.R().Delete(fmt.Sprintf("%s/%d/postmortems/%d", apiRoutes.incidents, *input.IncidentID, *input.PostmortemID))
	if err != nil {
		return nil, err
	}
	if apiErr := getGenericAPIError(resp, 204); apiErr != nil {
		return nil, apiErr
	}

	return &DeleteIncidentPostmortemOutput{}, nil
}

// overwriteQuery renders the optional overwrite parameter of the postmortem create operations
func overwriteQuery(overwrite *bool) string {
	if overwrite == nil {
		return ""
	}
	q := url.Values{}
	q.Add("overwrite", strconv.FormatBool(*overwrite))
	return "?" + q.Encode()
}
